package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildTidybeeAgent'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildTidybeeAgent")
    name = "build tidybee-agent"

    vcs {
        root(RelativeId("HttpsGithubComTidyBeeTidybeeBackendRefsHeadsMain2"))
    }

    steps {
        dockerCommand {
            commandType = build {
                source = file {
                    path = "agent/Dockerfile"
                }
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

